
// Generated by Cadence Encounter(R) RTL Compiler RC14.13 - v14.10-s027_1

// Verification Directory fv/train_FSM 

module train_FSM(clk, rst, depart_ready, door_obstruction,
     door_is_open, near_station, at_station, track_obstruction,
     cruise_speed, current_speed, crawl_speed, ctrl_door, ctrl_brake,
     ctrl_brake_emergency, ctrl_motor_accelerate, ctrl_motor_maintain);
  input clk, rst, depart_ready, door_obstruction, door_is_open,
       near_station, at_station, track_obstruction;
  input [7:0] cruise_speed, current_speed, crawl_speed;
  output ctrl_door, ctrl_brake, ctrl_brake_emergency,
       ctrl_motor_accelerate, ctrl_motor_maintain;
  wire clk, rst, depart_ready, door_obstruction, door_is_open,
       near_station, at_station, track_obstruction;
  wire [7:0] cruise_speed, current_speed, crawl_speed;
  wire ctrl_door, ctrl_brake, ctrl_brake_emergency,
       ctrl_motor_accelerate, ctrl_motor_maintain;
  wire [31:0] state;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_67, n_68, n_71, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_117, n_118, n_119, n_120, n_121, n_122, n_123, n_125;
  wire n_126;
  DFFSNQ_X1 \state_reg[1] (.SN (1'b1), .CLK (clk), .D (n_126), .Q
       (state[1]));
  NAND2_X1 g3867(.A1 (n_125), .A2 (n_92), .ZN (n_126));
  OAI21_X1 g3870(.A1 (n_122), .A2 (n_64), .B (state[1]), .ZN (n_125));
  DFFSNQ_X1 \state_reg[0] (.SN (1'b1), .CLK (clk), .D (n_123), .Q
       (state[0]));
  DFFSNQ_X1 \state_reg[2] (.SN (1'b1), .CLK (clk), .D (n_121), .Q
       (state[2]));
  OAI21_X1 g3868(.A1 (n_90), .A2 (n_86), .B (n_120), .ZN (n_123));
  DFFSNQ_X1 \state_reg[3] (.SN (1'b1), .CLK (clk), .D (n_119), .Q
       (state[3]));
  NOR3_X1 g3874(.A1 (n_117), .A2 (n_49), .A3 (rst), .ZN (n_122));
  NOR2_X1 g3875(.A1 (n_118), .A2 (rst), .ZN (n_121));
  AOI21_X1 g3869(.A1 (n_114), .A2 (n_91), .B (n_74), .ZN (n_120));
  OAI21_X1 g3876(.A1 (n_115), .A2 (n_73), .B (n_65), .ZN (n_119));
  INV_X1 g3877(.I (n_116), .ZN (n_118));
  AOI21_X1 g3879(.A1 (n_113), .A2 (n_107), .B (state[0]), .ZN (n_117));
  OAI22_X1 g3878(.A1 (n_111), .A2 (n_42), .B1 (n_30), .B2 (state[3]),
       .ZN (n_116));
  AOI21_X1 g3881(.A1 (n_53), .A2 (door_obstruction), .B (n_112), .ZN
       (n_115));
  AOI21_X1 g3873(.A1 (n_109), .A2 (n_19), .B (state[0]), .ZN (n_114));
  INV_X1 g3882(.I (n_112), .ZN (n_113));
  NOR2_X1 g3883(.A1 (n_110), .A2 (n_108), .ZN (n_112));
  NOR2_X1 g3884(.A1 (n_110), .A2 (n_1), .ZN (n_111));
  OAI22_X1 g3880(.A1 (n_106), .A2 (n_108), .B1 (n_107), .B2
       (at_station), .ZN (n_109));
  NOR2_X1 g3886(.A1 (n_105), .A2 (n_79), .ZN (n_110));
  NAND4_X1 g3885(.A1 (n_104), .A2 (n_83), .A3 (n_78), .A4 (n_3), .ZN
       (n_106));
  OAI22_X1 g3887(.A1 (n_103), .A2 (n_61), .B1 (n_10), .B2
       (current_speed[7]), .ZN (n_105));
  AOI22_X1 g3888(.A1 (n_102), .A2 (n_82), .B1 (n_8), .B2
       (current_speed[7]), .ZN (n_104));
  AOI22_X1 g3889(.A1 (n_100), .A2 (n_11), .B1 (n_101), .B2
       (crawl_speed[4]), .ZN (n_103));
  AOI21_X1 g3891(.A1 (n_101), .A2 (cruise_speed[4]), .B (n_99), .ZN
       (n_102));
  OAI21_X1 g3894(.A1 (n_96), .A2 (current_speed[3]), .B (n_98), .ZN
       (n_100));
  OAI22_X1 g3895(.A1 (n_95), .A2 (current_speed[3]), .B1 (n_94), .B2
       (n_93), .ZN (n_99));
  NAND2_X1 g3896(.A1 (n_97), .A2 (crawl_speed[3]), .ZN (n_98));
  NAND2_X1 g3899(.A1 (n_96), .A2 (current_speed[3]), .ZN (n_97));
  AND2_X1 g3898(.A1 (n_94), .A2 (n_93), .Z (n_95));
  AOI21_X1 g3890(.A1 (n_89), .A2 (n_91), .B (n_88), .ZN (n_92));
  AOI22_X1 g3901(.A1 (n_81), .A2 (crawl_speed[2]), .B1 (n_80), .B2
       (n_85), .ZN (n_96));
  NOR3_X1 g3892(.A1 (n_87), .A2 (n_89), .A3 (n_7), .ZN (n_90));
  NOR3_X1 g3893(.A1 (n_87), .A2 (n_86), .A3 (n_26), .ZN (n_88));
  AOI22_X1 g3902(.A1 (n_77), .A2 (n_85), .B1 (n_76), .B2
       (cruise_speed[2]), .ZN (n_94));
  TBUF_X1 ctrl_brake_tri(.EN (n_71), .I (n_75), .Z (ctrl_brake));
  OAI22_X1 g3897(.A1 (n_107), .A2 (n_59), .B1 (n_44), .B2
       (depart_ready), .ZN (n_87));
  NAND3_X1 g3903(.A1 (n_82), .A2 (n_0), .A3 (current_speed[4]), .ZN
       (n_83));
  OR2_X1 g3905(.A1 (n_80), .A2 (n_85), .Z (n_81));
  OAI22_X1 g3908(.A1 (n_57), .A2 (current_speed[5]), .B1 (n_36), .B2
       (current_speed[6]), .ZN (n_79));
  AOI21_X1 g3909(.A1 (n_35), .A2 (current_speed[6]), .B (n_68), .ZN
       (n_78));
  OR2_X1 g3904(.A1 (n_76), .A2 (cruise_speed[2]), .Z (n_77));
  NAND2_X1 g3906(.A1 (n_58), .A2 (n_62), .ZN (n_75));
  OAI21_X1 g3907(.A1 (n_54), .A2 (n_73), .B (n_48), .ZN (n_74));
  TBUF_X1 ctrl_door_tri(.EN (n_71), .I (n_63), .Z (ctrl_door));
  TBUF_X1 ctrl_motor_maintain_tri(.EN (n_71), .I (n_60), .Z
       (ctrl_motor_maintain));
  TBUF_X1 ctrl_brake_emergency_tri(.EN (n_71), .I (n_27), .Z
       (ctrl_brake_emergency));
  NOR2_X1 g3911(.A1 (n_67), .A2 (cruise_speed[5]), .ZN (n_68));
  OAI21_X1 g3912(.A1 (n_38), .A2 (cruise_speed[5]), .B (n_67), .ZN
       (n_82));
  TBUF_X1 ctrl_motor_accelerate_tri(.EN (n_71), .I (n_41), .Z
       (ctrl_motor_accelerate));
  OAI21_X1 g3914(.A1 (n_28), .A2 (current_speed[1]), .B (n_55), .ZN
       (n_80));
  AOI21_X1 g3921(.A1 (n_43), .A2 (n_14), .B (n_64), .ZN (n_65));
  NAND2_X1 g3924(.A1 (n_39), .A2 (n_62), .ZN (n_63));
  OAI21_X1 g3926(.A1 (n_2), .A2 (crawl_speed[5]), .B (n_56), .ZN
       (n_61));
  INV_X1 g3927(.I (n_52), .ZN (n_60));
  NOR4_X1 g3900(.A1 (n_20), .A2 (current_speed[2]), .A3
       (current_speed[0]), .A4 (current_speed[4]), .ZN (n_59));
  AOI21_X1 g3913(.A1 (n_50), .A2 (n_51), .B (n_46), .ZN (n_58));
  AOI22_X1 g3915(.A1 (n_34), .A2 (current_speed[1]), .B1 (n_33), .B2
       (n_32), .ZN (n_76));
  NAND2_X1 g3916(.A1 (n_56), .A2 (crawl_speed[5]), .ZN (n_57));
  NAND2_X1 g3917(.A1 (n_37), .A2 (current_speed[5]), .ZN (n_67));
  NAND2_X1 g3919(.A1 (n_29), .A2 (crawl_speed[1]), .ZN (n_55));
  NOR2_X1 g3920(.A1 (n_31), .A2 (n_6), .ZN (n_71));
  AOI21_X1 g3922(.A1 (n_53), .A2 (n_4), .B (n_16), .ZN (n_54));
  AOI22_X1 g3928(.A1 (n_45), .A2 (n_51), .B1 (n_50), .B2 (n_40), .ZN
       (n_52));
  NOR2_X1 g3918(.A1 (n_13), .A2 (n_47), .ZN (n_49));
  NAND2_X1 g3923(.A1 (n_47), .A2 (n_17), .ZN (n_48));
  OAI22_X1 g3929(.A1 (n_45), .A2 (n_44), .B1 (n_43), .B2 (n_42), .ZN
       (n_46));
  AND2_X1 g3940(.A1 (n_45), .A2 (n_40), .Z (n_41));
  NAND2_X1 g3943(.A1 (n_50), .A2 (n_53), .ZN (n_39));
  AOI21_X1 g3946(.A1 (n_108), .A2 (door_is_open), .B (n_15), .ZN
       (n_64));
  INV_X1 g3947(.I (n_24), .ZN (n_56));
  INV_X1 g3949(.I (n_37), .ZN (n_38));
  NAND2_X1 g3930(.A1 (n_23), .A2 (crawl_speed[6]), .ZN (n_36));
  NOR2_X1 g3931(.A1 (n_21), .A2 (cruise_speed[6]), .ZN (n_35));
  OR2_X1 g3932(.A1 (n_33), .A2 (n_32), .Z (n_34));
  NOR2_X1 g3935(.A1 (n_25), .A2 (n_30), .ZN (n_31));
  NAND2_X1 g3938(.A1 (n_28), .A2 (current_speed[1]), .ZN (n_29));
  NOR2_X1 g3939(.A1 (n_30), .A2 (n_42), .ZN (n_27));
  NOR2_X1 g3941(.A1 (n_42), .A2 (near_station), .ZN (n_26));
  OR2_X1 g3942(.A1 (n_43), .A2 (rst), .Z (n_73));
  OR2_X1 g3944(.A1 (n_25), .A2 (n_43), .Z (n_62));
  OAI21_X1 g3948(.A1 (n_22), .A2 (crawl_speed[6]), .B (n_23), .ZN
       (n_24));
  AOI21_X1 g3950(.A1 (n_22), .A2 (cruise_speed[6]), .B (n_21), .ZN
       (n_37));
  NAND2_X1 g3910(.A1 (n_12), .A2 (n_22), .ZN (n_20));
  NAND2_X1 g3933(.A1 (state[0]), .A2 (n_91), .ZN (n_86));
  NAND2_X1 g3934(.A1 (n_19), .A2 (n_18), .ZN (n_89));
  NAND2_X1 g3936(.A1 (n_107), .A2 (n_18), .ZN (n_47));
  NOR2_X1 g3937(.A1 (n_30), .A2 (rst), .ZN (n_17));
  NAND2_X1 g3945(.A1 (n_19), .A2 (n_5), .ZN (n_16));
  INV_X1 g3963(.I (n_44), .ZN (n_53));
  INV_X1 g3967(.I (n_14), .ZN (n_15));
  INV_X1 g3971(.I (n_42), .ZN (n_40));
  INV_X1 g3973(.I (n_25), .ZN (n_51));
  NAND2_X1 g3969(.A1 (state[1]), .A2 (n_13), .ZN (n_43));
  NOR4_X1 g3925(.A1 (current_speed[7]), .A2 (current_speed[1]), .A3
       (current_speed[5]), .A4 (current_speed[3]), .ZN (n_12));
  NAND2_X1 g3972(.A1 (n_107), .A2 (state[2]), .ZN (n_42));
  NAND2_X1 g3974(.A1 (state[3]), .A2 (n_108), .ZN (n_25));
  NOR2_X1 g3970(.A1 (state[1]), .A2 (n_13), .ZN (n_50));
  NOR2_X1 g3968(.A1 (n_107), .A2 (rst), .ZN (n_14));
  NAND2_X1 g3951(.A1 (n_9), .A2 (cruise_speed[0]), .ZN (n_33));
  OR2_X1 g3952(.A1 (n_101), .A2 (crawl_speed[4]), .Z (n_11));
  NAND2_X1 g3953(.A1 (n_10), .A2 (current_speed[7]), .ZN (n_23));
  NOR2_X1 g3954(.A1 (n_9), .A2 (crawl_speed[0]), .ZN (n_28));
  NOR2_X1 g3955(.A1 (n_8), .A2 (current_speed[7]), .ZN (n_21));
  NOR2_X1 g3956(.A1 (n_108), .A2 (near_station), .ZN (n_7));
  NAND2_X1 g3964(.A1 (n_107), .A2 (n_108), .ZN (n_44));
  INV_X1 g3965(.I (n_19), .ZN (n_6));
  NAND2_X1 g3960(.A1 (state[3]), .A2 (door_is_open), .ZN (n_5));
  NAND2_X1 g3962(.A1 (state[1]), .A2 (state[0]), .ZN (n_30));
  NOR2_X1 g3958(.A1 (door_obstruction), .A2 (door_is_open), .ZN (n_4));
  NOR2_X1 g3957(.A1 (state[1]), .A2 (rst), .ZN (n_91));
  NAND2_X1 g3959(.A1 (state[2]), .A2 (track_obstruction), .ZN (n_18));
  NOR2_X1 g3961(.A1 (state[1]), .A2 (state[0]), .ZN (n_45));
  NAND2_X1 g3966(.A1 (state[3]), .A2 (state[2]), .ZN (n_19));
  INV_X1 g3984(.I (current_speed[2]), .ZN (n_85));
  INV_X1 g3986(.I (track_obstruction), .ZN (n_3));
  INV_X1 g3980(.I (current_speed[0]), .ZN (n_9));
  INV_X1 g3985(.I (cruise_speed[7]), .ZN (n_8));
  INV_X1 g3979(.I (cruise_speed[1]), .ZN (n_32));
  INV_X1 g3982(.I (cruise_speed[3]), .ZN (n_93));
  INV_X1 g3983(.I (current_speed[5]), .ZN (n_2));
  INV_X1 g3981(.I (crawl_speed[7]), .ZN (n_10));
  INV_X1 g3978(.I (state[3]), .ZN (n_107));
  INV_X1 g3987(.I (current_speed[6]), .ZN (n_22));
  INV_X1 g3975(.I (state[2]), .ZN (n_108));
  INV_X1 g3976(.I (state[1]), .ZN (n_1));
  INV_X1 g3989(.I (current_speed[4]), .ZN (n_101));
  INV_X1 g3988(.I (cruise_speed[4]), .ZN (n_0));
  INV_X1 g3977(.I (state[0]), .ZN (n_13));
endmodule

